<!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center">The IOU mission is to improve lives through learning. Our global marketplace features extensive, multi-language courses taught by expert instructors. You can take courses across a wide range of categories, some of which include: business &amp; entrepreneurship, programming, academics, the arts, health &amp; fitness, language, music, and much more!</p>
<!-- /wp:paragraph -->


<div class="wp-block-qubely-text aligncenter qubely-block-3ec728">
    <div class="qubely-block-text  ">
        <div class="qubely-block-text-title-container  qubely-separator-position-top">
            <div class="qubely-block-text-title-inner">
                <p></p>
                <h2 class="qubely-block-text-title">
                    <span style="color: #f87793;" data="#f87793" class="qubely-text-has-color">Instructor</span>
                </h2>
                <p></p>
            </div>
        </div>
        <p></p>
    </div>
</div>
        <!-- wp:qubely/accordion {"uniqueId":"f1f77c","animation":{"animation":"","name":"Center","repeat":"once","direction":"Center","duration":1000,"delay":0,"curve":"ease-in-out","openAnimation":0},"interaction":{"while_scroll_into_view":{"enable":false,"action_list":[{"id":"b3fdc1c1e6bfde5942ea","index":0,"keyframe":0,"name":"move","property":{"x":0,"y":-100,"z":0},"range":{"max":1000,"min":-1000,"step":1},"single":true,"title":"Move"},{"id":"936e0225e6dc8edfba7d","index":1,"keyframe":100,"name":"move","property":{"x":0,"y":0,"z":0},"range":{"max":1000,"min":-1000,"step":1},"single":true,"title":"Move"}],"transform_origin_x":"center","transform_origin_y":"center","enable_mobile":false,"enable_tablet":false},"mouse_movement":{"enable":false,"mouse_tilt_direction":"Direct","mouse_tilt_speed":1,"mouse_tilt_max":15,"enable_mobile":false,"enable_tablet":false}},"positionXaxis":{"md":"","unit":"px"},"positionYaxis":{"md":"","unit":"px"}} -->
<div class="qubely-block-accordion  qubely-block-f1f77c" data-item-toggle="true"><!-- wp:qubely/accordion-item {"uniqueId":"9b8b4d","itemNumber":-1,"heading":"How do I register as a IOU instructor?","active":true,"panelColor":"var(\u002d\u002dqubely-color-3)","panelBg":{"openColor":1,"type":"color","color":"rgba(254,241,243,0.75)","gradient":{"color1":"#EEEEEE","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"panelBgActive":{"openColor":1,"type":"color","color":"#fc8ba1","gradient":{"color1":"#2476CA","color2":"#1A5FA4","direction":0,"start":0,"stop":100,"type":"linear"}},"panelBorder":{"borderType":"global"},"panelBorderColorActive":{"borderType":"global"},"panelBoxShadow":{},"panelBoxShadowActive":{},"typography":{"openTypography":false},"panelPadding":{"openPadding":1,"paddingType":"global","global":{"md":15},"unit":"px"},"panelBorderRadius":{"radiusType":"global","global":{"md":"3"},"unit":"px","openBorderRadius":1},"panelBorderRadiusActive":{"radiusType":"global"},"bodyBg":{"openColor":1,"type":"color","color":"rgba(239,239,239,0.18)","gradient":{"color1":"#f2f2f2","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"bodyPadding":{"openPadding":1,"paddingType":"global","global":{"md":15},"unit":"px"},"bodyPaddingAlt":{"openPadding":1,"paddingType":"custom","custom":{"md":"15 0 0 0"},"unit":"px"},"bodyBoxShadow":{},"bodyBorder":{"borderType":"global"},"borderRadius":{"radiusType":"global","global":{"md":""},"unit":"px","openBorderRadius":1},"iconSpacing":{"md":10,"unit":"px"},"spacing":{"md":"25","unit":"px"}} -->
            <div class="wp-block-qubely-accordion-item qubely-block-9b8b4d"><div class="qubely-accordion-item qubely-type-fill false"><div class="qubely-accordion-panel qubely-icon-position-right"><span class="qubely-accordion-panel-handler" role="button"><span class="qubely-accordion-panel-handler-label">How do I register as a IOU instructor?</span><span class="qubely-accordion-icon fa fa-plus"></span></span></div><div class="qubely-accordion-body"><div itemprop="text"><!-- wp:paragraph -->
                            <p><a href="https://iou.ac/iou-instructor-guideline/" target="_blank" rel="noreferrer noopener">Click here</a> to visit the <a href="https://iou.ac/iou-instructor-guideline/" target="_blank" rel="noreferrer noopener">instructor guideline</a> page and know how to apply to become an instructior.</p>
                            <!-- /wp:paragraph --></div></div></div></div>
            <!-- /wp:qubely/accordion-item -->

            <!-- wp:qubely/accordion-item {"uniqueId":"b5f951","itemNumber":5,"heading":"Can I choose any topic to develop a course?","panelColor":"var(\u002d\u002dqubely-color-3)","panelBg":{"openColor":1,"type":"color","color":"rgba(254,241,243,0.75)","gradient":{"color1":"#EEEEEE","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"panelBgActive":{"openColor":1,"type":"color","color":"#fc8ba1","gradient":{"color1":"#2476CA","color2":"#1A5FA4","direction":0,"start":0,"stop":100,"type":"linear"}},"panelBorder":{"borderType":"global"},"panelBorderColorActive":{"borderType":"global"},"panelBoxShadow":{},"panelBoxShadowActive":{},"typography":{"openTypography":false},"panelPadding":{"openPadding":1,"paddingType":"global","global":{"md":15},"unit":"px"},"panelBorderRadius":{"radiusType":"global","global":{"md":"3"},"unit":"px","openBorderRadius":1},"panelBorderRadiusActive":{"radiusType":"global"},"bodyBg":{"openColor":1,"type":"color","color":"rgba(239,239,239,0.18)","gradient":{"color1":"#f2f2f2","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"bodyPadding":{"openPadding":1,"paddingType":"global","global":{"md":15},"unit":"px"},"bodyPaddingAlt":{"openPadding":1,"paddingType":"custom","custom":{"md":"15 0 0 0"},"unit":"px"},"bodyBoxShadow":{},"bodyBorder":{"borderType":"global"},"borderRadius":{"radiusType":"global","global":{"md":""},"unit":"px","openBorderRadius":1},"iconSpacing":{"md":10,"unit":"px"},"spacing":{"md":"25","unit":"px"}} -->
            <div class="wp-block-qubely-accordion-item qubely-block-b5f951"><div class="qubely-accordion-item qubely-type-fill false"><div class="qubely-accordion-panel qubely-icon-position-right"><span class="qubely-accordion-panel-handler" role="button"><span class="qubely-accordion-panel-handler-label">Can I choose any topic to develop a course?</span><span class="qubely-accordion-icon fa fa-plus"></span></span></div><div class="qubely-accordion-body"><div itemprop="text"><!-- wp:paragraph -->
                            <p>You are free to choose the topic you wish to teach on IOU, but before that, you are kindly requested to analyze the market demand and choose a skill-based topic to work on.</p>
                            <!-- /wp:paragraph --></div></div></div></div>
            <!-- /wp:qubely/accordion-item -->

            <!-- wp:qubely/accordion-item {"uniqueId":"947a29","itemNumber":1,"heading":"Do I have to pay any fees in order to become an instructor?","panelColor":"var(\u002d\u002dqubely-color-3)","panelBg":{"openColor":1,"type":"color","color":"rgba(254,241,243,0.75)","gradient":{"color1":"#EEEEEE","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"panelBgActive":{"openColor":1,"type":"color","color":"#fc8ba1","gradient":{"color1":"#2476CA","color2":"#1A5FA4","direction":0,"start":0,"stop":100,"type":"linear"}},"panelBorder":{"borderType":"global"},"panelBorderColorActive":{"borderType":"global"},"panelBoxShadow":{},"panelBoxShadowActive":{},"typography":{"openTypography":false},"panelPadding":{"openPadding":1,"paddingType":"global","global":{"md":15},"unit":"px"},"panelBorderRadius":{"radiusType":"global","global":{"md":"3"},"unit":"px","openBorderRadius":1},"panelBorderRadiusActive":{"radiusType":"global"},"bodyBg":{"openColor":1,"type":"color","color":"rgba(239,239,239,0.18)","gradient":{"color1":"#f2f2f2","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"bodyPadding":{"openPadding":1,"paddingType":"global","global":{"md":15},"unit":"px"},"bodyPaddingAlt":{"openPadding":1,"paddingType":"custom","custom":{"md":"15 0 0 0"},"unit":"px"},"bodyBoxShadow":{},"bodyBorder":{"borderType":"global"},"borderRadius":{"radiusType":"global","global":{"md":""},"unit":"px","openBorderRadius":1},"iconSpacing":{"md":10,"unit":"px"},"spacing":{"md":"25","unit":"px"}} -->
            <div class="wp-block-qubely-accordion-item qubely-block-947a29"><div class="qubely-accordion-item qubely-type-fill false"><div class="qubely-accordion-panel qubely-icon-position-right"><span class="qubely-accordion-panel-handler" role="button"><span class="qubely-accordion-panel-handler-label">Do I have to pay any fees in order to become an instructor?</span><span class="qubely-accordion-icon fa fa-plus"></span></span></div><div class="qubely-accordion-body"><div itemprop="text"><!-- wp:paragraph -->
                            <p>There is no fee to be an instructor on IOU. Instead, instructors are paid according to a revenue share model. Visit our instructor policy and learn more.</p>
                            <!-- /wp:paragraph --></div></div></div></div>
            <!-- /wp:qubely/accordion-item -->

            <!-- wp:qubely/accordion-item {"uniqueId":"e3ff4d","itemNumber":2,"heading":"What approval do I need to get started as an instructor?","panelColor":"var(\u002d\u002dqubely-color-3)","panelBg":{"openColor":1,"type":"color","color":"rgba(254,241,243,0.75)","gradient":{"color1":"#EEEEEE","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"panelBgActive":{"openColor":1,"type":"color","color":"#fc8ba1","gradient":{"color1":"#2476CA","color2":"#1A5FA4","direction":0,"start":0,"stop":100,"type":"linear"}},"panelBorder":{"borderType":"global"},"panelBorderColorActive":{"borderType":"global"},"panelBoxShadow":{},"panelBoxShadowActive":{},"typography":{"openTypography":false},"panelPadding":{"openPadding":1,"paddingType":"global","global":{"md":15},"unit":"px"},"panelBorderRadius":{"radiusType":"global","global":{"md":"3"},"unit":"px","openBorderRadius":1},"panelBorderRadiusActive":{"radiusType":"global"},"bodyBg":{"openColor":1,"type":"color","color":"rgba(239,239,239,0.18)","gradient":{"color1":"#f2f2f2","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"bodyPadding":{"openPadding":1,"paddingType":"global","global":{"md":15},"unit":"px"},"bodyPaddingAlt":{"openPadding":1,"paddingType":"custom","custom":{"md":"15 0 0 0"},"unit":"px"},"bodyBoxShadow":{},"bodyBorder":{"borderType":"global"},"borderRadius":{"radiusType":"global","global":{"md":""},"unit":"px","openBorderRadius":1},"iconSpacing":{"md":10,"unit":"px"},"spacing":{"md":"25","unit":"px"}} -->
            <div class="wp-block-qubely-accordion-item qubely-block-e3ff4d"><div class="qubely-accordion-item qubely-type-fill false"><div class="qubely-accordion-panel qubely-icon-position-right"><span class="qubely-accordion-panel-handler" role="button"><span class="qubely-accordion-panel-handler-label">What approval do I need to get started as an instructor?</span><span class="qubely-accordion-icon fa fa-plus"></span></span></div><div class="qubely-accordion-body"><div itemprop="text"><!-- wp:paragraph -->
                            <p>It is necessary to complete your profile 100% before applying to be an instructor. Also, read the <a href="https://docs.google.com/document/d/1nc4smWIte8jfqeIo3cclVNMCVhywn1YPB_T_ygfvZRU/preview" target="_blank" rel="noreferrer noopener">Instructor Agreement</a> and fill up &amp; submit the <a href="https://forms.gle/EjnZxyvxiBiuQuSZ8" target="_blank" rel="noreferrer noopener">Terms and Non-disclosure Agreement Form</a>.If everything is fine, the IOU team will approve the instructor profile within 2 working days.</p>
                            <!-- /wp:paragraph --></div></div></div></div>
            <!-- /wp:qubely/accordion-item -->

            <!-- wp:qubely/accordion-item {"uniqueId":"25a88d","itemNumber":3,"heading":"Are there any requirements that my course must meet?","panelColor":"var(\u002d\u002dqubely-color-3)","panelBg":{"openColor":1,"type":"color","color":"rgba(254,241,243,0.75)","gradient":{"color1":"#EEEEEE","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"panelBgActive":{"openColor":1,"type":"color","color":"#fc8ba1","gradient":{"color1":"#2476CA","color2":"#1A5FA4","direction":0,"start":0,"stop":100,"type":"linear"}},"panelBorder":{"borderType":"global"},"panelBorderColorActive":{"borderType":"global"},"panelBoxShadow":{},"panelBoxShadowActive":{},"typography":{"openTypography":false},"panelPadding":{"openPadding":1,"paddingType":"global","global":{"md":15},"unit":"px"},"panelBorderRadius":{"radiusType":"global","global":{"md":"3"},"unit":"px","openBorderRadius":1},"panelBorderRadiusActive":{"radiusType":"global"},"bodyBg":{"openColor":1,"type":"color","color":"rgba(239,239,239,0.18)","gradient":{"color1":"#f2f2f2","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"bodyPadding":{"openPadding":1,"paddingType":"global","global":{"md":15},"unit":"px"},"bodyPaddingAlt":{"openPadding":1,"paddingType":"custom","custom":{"md":"15 0 0 0"},"unit":"px"},"bodyBoxShadow":{},"bodyBorder":{"borderType":"global"},"borderRadius":{"radiusType":"global","global":{"md":""},"unit":"px","openBorderRadius":1},"iconSpacing":{"md":10,"unit":"px"},"spacing":{"md":"25","unit":"px"}} -->
            <div class="wp-block-qubely-accordion-item qubely-block-25a88d"><div class="qubely-accordion-item qubely-type-fill false"><div class="qubely-accordion-panel qubely-icon-position-right"><span class="qubely-accordion-panel-handler" role="button"><span class="qubely-accordion-panel-handler-label">Are there any requirements that my course must meet?</span><span class="qubely-accordion-icon fa fa-plus"></span></span></div><div class="qubely-accordion-body"><div itemprop="text"><!-- wp:paragraph -->
                            <p>Yes. Courses must have at least 30 minutes of video content and at least 5 lectures or learning modules.<br>In order to ensure that students have great learning experiences, we also have <a href="https://iou.ac/quality-standards/">Quality standards.</a></p>
                            <!-- /wp:paragraph --></div></div></div></div>
            <!-- /wp:qubely/accordion-item -->

            <!-- wp:qubely/accordion-item {"uniqueId":"53a0c1","itemNumber":5,"heading":"How do I create a IOU course and upload contents?","panelColor":"var(\u002d\u002dqubely-color-3)","panelBg":{"openColor":1,"type":"color","color":"rgba(254,241,243,0.75)","gradient":{"color1":"#EEEEEE","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"panelBgActive":{"openColor":1,"type":"color","color":"#fc8ba1","gradient":{"color1":"#2476CA","color2":"#1A5FA4","direction":0,"start":0,"stop":100,"type":"linear"}},"panelBorder":{"borderType":"global"},"panelBorderColorActive":{"borderType":"global"},"panelBoxShadow":{},"panelBoxShadowActive":{},"typography":{"openTypography":false},"panelPadding":{"openPadding":1,"paddingType":"global","global":{"md":15},"unit":"px"},"panelBorderRadius":{"radiusType":"global","global":{"md":"3"},"unit":"px","openBorderRadius":1},"panelBorderRadiusActive":{"radiusType":"global"},"bodyBg":{"openColor":1,"type":"color","color":"rgba(239,239,239,0.18)","gradient":{"color1":"#f2f2f2","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"bodyPadding":{"openPadding":1,"paddingType":"global","global":{"md":15},"unit":"px"},"bodyPaddingAlt":{"openPadding":1,"paddingType":"custom","custom":{"md":"15 0 0 0"},"unit":"px"},"bodyBoxShadow":{},"bodyBorder":{"borderType":"global"},"borderRadius":{"radiusType":"global","global":{"md":""},"unit":"px","openBorderRadius":1},"iconSpacing":{"md":10,"unit":"px"},"spacing":{"md":"25","unit":"px"}} -->
            <div class="wp-block-qubely-accordion-item qubely-block-53a0c1"><div class="qubely-accordion-item qubely-type-fill false"><div class="qubely-accordion-panel qubely-icon-position-right"><span class="qubely-accordion-panel-handler" role="button"><span class="qubely-accordion-panel-handler-label">How do I create a IOU course and upload contents?</span><span class="qubely-accordion-icon fa fa-plus"></span></span></div><div class="qubely-accordion-body"><div itemprop="text"><!-- wp:paragraph -->
                            <p>Visit <a href="https://iou.ac/iou-instructor-guideline/" target="_blank" rel="noreferrer noopener">IOU Instructor Guideline</a> to create your course &amp; upload contents. </p>
                            <!-- /wp:paragraph --></div></div></div></div>
            <!-- /wp:qubely/accordion-item -->

            <!-- wp:qubely/accordion-item {"uniqueId":"93bcff","itemNumber":4,"heading":"How will I get paid?","panelColor":"var(\u002d\u002dqubely-color-3)","panelBg":{"openColor":1,"type":"color","color":"rgba(254,241,243,0.75)","gradient":{"color1":"#EEEEEE","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"panelBgActive":{"openColor":1,"type":"color","color":"#fc8ba1","gradient":{"color1":"#2476CA","color2":"#1A5FA4","direction":0,"start":0,"stop":100,"type":"linear"}},"panelBorder":{"borderType":"global"},"panelBorderColorActive":{"borderType":"global"},"panelBoxShadow":{},"panelBoxShadowActive":{},"typography":{"openTypography":false},"panelPadding":{"openPadding":1,"paddingType":"global","global":{"md":15},"unit":"px"},"panelBorderRadius":{"radiusType":"global","global":{"md":"3"},"unit":"px","openBorderRadius":1},"panelBorderRadiusActive":{"radiusType":"global"},"bodyBg":{"openColor":1,"type":"color","color":"rgba(239,239,239,0.18)","gradient":{"color1":"#f2f2f2","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"bodyPadding":{"openPadding":1,"paddingType":"global","global":{"md":15},"unit":"px"},"bodyPaddingAlt":{"openPadding":1,"paddingType":"custom","custom":{"md":"15 0 0 0"},"unit":"px"},"bodyBoxShadow":{},"bodyBorder":{"borderType":"global"},"borderRadius":{"radiusType":"global","global":{"md":""},"unit":"px","openBorderRadius":1},"iconSpacing":{"md":10,"unit":"px"},"spacing":{"md":"25","unit":"px"}} -->
            <div class="wp-block-qubely-accordion-item qubely-block-93bcff"><div class="qubely-accordion-item qubely-type-fill false"><div class="qubely-accordion-panel qubely-icon-position-right"><span class="qubely-accordion-panel-handler" role="button"><span class="qubely-accordion-panel-handler-label">How will I get paid?</span><span class="qubely-accordion-icon fa fa-plus"></span></span></div><div class="qubely-accordion-body"><div itemprop="text"><!-- wp:paragraph -->
                            <p>Instructors can use PayPal, Payoneer to receive their payments. You are paid on a monthly basis. As an instructor, you will receive 70% of the royalty of the course.</p>
                            <!-- /wp:paragraph -->
                        </div>
                    </div>
                </div>
            </div>
            <!-- /wp:qubely/accordion-item -->
</div>



<div class="wp-block-qubely-text aligncenter qubely-block-3ec728">
    <div class="qubely-block-text  ">
        <div class="qubely-block-text-title-container  qubely-separator-position-top">
            <div class="qubely-block-text-title-inner">
               <p></p>
                <h2 class="qubely-block-text-title">
                    <span style="color: #f87793;" data="#f87793" class="qubely-text-has-color">Student</span>
                </h2>
                <p></p>

            </div>
        </div>
        <p></p>
    </div>
</div>
<!-- wp:qubely/accordion {"uniqueId":"b4a8c1","animation":{"animation":"","name":"Center","repeat":"once","direction":"Center","duration":1000,"delay":0,"curve":"ease-in-out","openAnimation":0},"interaction":{"while_scroll_into_view":{"enable":false,"action_list":[{"id":"b3fdc1c1e6bfde5942ea","index":0,"keyframe":0,"name":"move","property":{"x":0,"y":-100,"z":0},"range":{"max":1000,"min":-1000,"step":1},"single":true,"title":"Move"},{"id":"936e0225e6dc8edfba7d","index":1,"keyframe":100,"name":"move","property":{"x":0,"y":0,"z":0},"range":{"max":1000,"min":-1000,"step":1},"single":true,"title":"Move"}],"transform_origin_x":"center","transform_origin_y":"center","enable_mobile":false,"enable_tablet":false},"mouse_movement":{"enable":false,"mouse_tilt_direction":"Direct","mouse_tilt_speed":1,"mouse_tilt_max":15,"enable_mobile":false,"enable_tablet":false}}} -->
<div class="qubely-block-accordion  qubely-block-b4a8c1" data-item-toggle="true"><!-- wp:qubely/accordion-item {"uniqueId":"0ff295","itemNumber":0,"heading":"What does IOU stand for?","defaultText":"Create stylish call-to-action buttons with Qubely Buttons. Play around with typography, design, border and more. Add animations and personalize it to engage visitors instantly.","panelColor":"var(\u002d\u002dqubely-color-3)","panelBg":{"openColor":1,"type":"color","color":"rgba(254,241,243,0.75)","gradient":{"color1":"#EEEEEE","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"panelBgActive":{"openColor":1,"type":"color","color":"#fc8ba1","gradient":{"color1":"#2476CA","color2":"#1A5FA4","direction":0,"start":0,"stop":100,"type":"linear"}},"typography":{"openTypography":false},"panelBorderRadius":{"radiusType":"global","global":{"md":"3"},"unit":"px","openBorderRadius":1},"bodyBg":{"openColor":1,"type":"color","color":"rgba(239,239,239,0.18)","gradient":{"color1":"#f2f2f2","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"borderRadius":{"radiusType":"global","global":{"md":""},"unit":"px","openBorderRadius":1},"spacing":{"md":"25","unit":"px"}} -->
    <div class="wp-block-qubely-accordion-item qubely-block-0ff295"><div class="qubely-accordion-item qubely-type-fill qubely-accordion-active"><div class="qubely-accordion-panel qubely-icon-position-right"><span class="qubely-accordion-panel-handler" role="button"><span class="qubely-accordion-panel-handler-label">What does IOU stand for?</span><span class="qubely-accordion-icon fa fa-plus"></span></span></div><div class="qubely-accordion-body" style="display:block"><div itemprop="text"><!-- wp:paragraph -->
                    <p><strong>International Open University</strong></p>
                    <!-- /wp:paragraph -->

                    <!-- wp:paragraph -->
                    <p>IOU is an online education provider that offers online courses from top universities, individual instructors, and companies around the world.</p>
                    <!-- /wp:paragraph --></div></div></div></div>
    <!-- /wp:qubely/accordion-item -->

    <!-- wp:qubely/accordion-item {"uniqueId":"6dba99","itemNumber":1,"heading":"How can I enroll in a course?","defaultText":"Create stylish call-to-action buttons with Qubely Buttons. Play around with typography, design, border and more. Add animations and personalize it to engage visitors instantly.","panelColor":"var(\u002d\u002dqubely-color-3)","panelBg":{"openColor":1,"type":"color","color":"rgba(254,241,243,0.75)","gradient":{"color1":"#EEEEEE","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"panelBgActive":{"openColor":1,"type":"color","color":"#fc8ba1","gradient":{"color1":"#2476CA","color2":"#1A5FA4","direction":0,"start":0,"stop":100,"type":"linear"}},"typography":{"openTypography":false},"panelBorderRadius":{"radiusType":"global","global":{"md":"3"},"unit":"px","openBorderRadius":1},"bodyBg":{"openColor":1,"type":"color","color":"rgba(239,239,239,0.18)","gradient":{"color1":"#f2f2f2","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"borderRadius":{"radiusType":"global","global":{"md":""},"unit":"px","openBorderRadius":1},"spacing":{"md":"25","unit":"px"}} -->
    <div class="wp-block-qubely-accordion-item qubely-block-6dba99"><div class="qubely-accordion-item qubely-type-fill false"><div class="qubely-accordion-panel qubely-icon-position-right"><span class="qubely-accordion-panel-handler" role="button"><span class="qubely-accordion-panel-handler-label">How can I enroll in a course?</span><span class="qubely-accordion-icon fa fa-plus"></span></span></div><div class="qubely-accordion-body"><div itemprop="text"><!-- wp:paragraph -->
                    <p>IOU courses are entirely on-demand. You can begin the course whenever you like, and there are no deadlines to complete it. IOU courses can be accessed from several different devices and platforms, including a desktop, laptop, and IOU mobile app.&nbsp;</p>
                    <!-- /wp:paragraph -->

                    <!-- wp:paragraph -->
                    <p>After you enroll in a course, you can access the course directly from the IOU platform. After login, click on the profile icon on the top right and select 'Enrolled Courses'. On this page, you will see all the courses that you have enrolled in. You can go to the course content page by clicking on the course name/featured image. Also, you will receive an email with the course link from IOU after you enroll in any course.</p>
                    <!-- /wp:paragraph -->

                    <!-- wp:image {"id":6579,"sizeSlug":"large","linkDestination":"none"} -->
                    <figure class="wp-block-image size-large"><img src="https://iou.ac/wp-content/uploads/2021/04/Screenshot-178-1024x368.png" alt="" class="wp-image-6579"/></figure>
                    <!-- /wp:image --></div></div></div></div>
    <!-- /wp:qubely/accordion-item -->

    <!-- wp:qubely/accordion-item {"uniqueId":"f92bb3","itemNumber":5,"heading":"Are courses on IOU free?","panelColor":"var(\u002d\u002dqubely-color-3)","panelBg":{"openColor":1,"type":"color","color":"rgba(254,241,243,0.75)","gradient":{"color1":"#EEEEEE","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"panelBgActive":{"openColor":1,"type":"color","color":"#fc8ba1","gradient":{"color1":"#2476CA","color2":"#1A5FA4","direction":0,"start":0,"stop":100,"type":"linear"}},"typography":{"openTypography":false},"panelBorderRadius":{"radiusType":"global","global":{"md":"3"},"unit":"px","openBorderRadius":1},"bodyBg":{"openColor":1,"type":"color","color":"rgba(239,239,239,0.18)","gradient":{"color1":"#f2f2f2","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"borderRadius":{"radiusType":"global","global":{"md":""},"unit":"px","openBorderRadius":1},"spacing":{"md":"25","unit":"px"}} -->
    <div class="wp-block-qubely-accordion-item qubely-block-f92bb3"><div class="qubely-accordion-item qubely-type-fill false"><div class="qubely-accordion-panel qubely-icon-position-right"><span class="qubely-accordion-panel-handler" role="button"><span class="qubely-accordion-panel-handler-label">Are courses on IOU free?</span><span class="qubely-accordion-icon fa fa-plus"></span></span></div><div class="qubely-accordion-body"><div itemprop="text"><!-- wp:paragraph -->
                    <p>In IOU platform we have both free and paid coureses. Feel free explore the courses from <a href="https://iou.ac/courses/" target="_blank" rel="noreferrer noopener">here</a>.</p>
                    <!-- /wp:paragraph --></div></div></div></div>
    <!-- /wp:qubely/accordion-item -->

    <!-- wp:qubely/accordion-item {"uniqueId":"851e43","itemNumber":2,"heading":"Can I preview a course or lesson?","panelColor":"var(\u002d\u002dqubely-color-3)","panelBg":{"openColor":1,"type":"color","color":"rgba(254,241,243,0.75)","gradient":{"color1":"#EEEEEE","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"panelBgActive":{"openColor":1,"type":"color","color":"#fc8ba1","gradient":{"color1":"#2476CA","color2":"#1A5FA4","direction":0,"start":0,"stop":100,"type":"linear"}},"typography":{"openTypography":false},"panelBorderRadius":{"radiusType":"global","global":{"md":"3"},"unit":"px","openBorderRadius":1},"bodyBg":{"openColor":1,"type":"color","color":"rgba(239,239,239,0.18)","gradient":{"color1":"#f2f2f2","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"borderRadius":{"radiusType":"global","global":{"md":""},"unit":"px","openBorderRadius":1},"spacing":{"md":"25","unit":"px"}} -->
    <div class="wp-block-qubely-accordion-item qubely-block-851e43"><div class="qubely-accordion-item qubely-type-fill false"><div class="qubely-accordion-panel qubely-icon-position-right"><span class="qubely-accordion-panel-handler" role="button"><span class="qubely-accordion-panel-handler-label">Can I preview a course or lesson?</span><span class="qubely-accordion-icon fa fa-plus"></span></span></div><div class="qubely-accordion-body"><div itemprop="text"><!-- wp:paragraph -->
                    <p>You can preview the introduction videos of every course which will give you an idea about what you will learn from the course. For free courses, you can access every video &amp; course content after you enroll in the course. For Paid courses, you need to pay the course enrollment fee through PayPal, and then you can access all the contents.</p>
                    <!-- /wp:paragraph --></div></div></div></div>
    <!-- /wp:qubely/accordion-item -->

    <!-- wp:qubely/accordion-item {"uniqueId":"6407ab","itemNumber":3,"heading":"How long I can access the enrolled courses?","panelColor":"var(\u002d\u002dqubely-color-3)","panelBg":{"openColor":1,"type":"color","color":"rgba(254,241,243,0.75)","gradient":{"color1":"#EEEEEE","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"panelBgActive":{"openColor":1,"type":"color","color":"#fc8ba1","gradient":{"color1":"#2476CA","color2":"#1A5FA4","direction":0,"start":0,"stop":100,"type":"linear"}},"typography":{"openTypography":false},"panelBorderRadius":{"radiusType":"global","global":{"md":"3"},"unit":"px","openBorderRadius":1},"bodyBg":{"openColor":1,"type":"color","color":"rgba(239,239,239,0.18)","gradient":{"color1":"#f2f2f2","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"borderRadius":{"radiusType":"global","global":{"md":""},"unit":"px","openBorderRadius":1},"spacing":{"md":"25","unit":"px"}} -->
    <div class="wp-block-qubely-accordion-item qubely-block-6407ab"><div class="qubely-accordion-item qubely-type-fill false"><div class="qubely-accordion-panel qubely-icon-position-right"><span class="qubely-accordion-panel-handler" role="button"><span class="qubely-accordion-panel-handler-label">How long I can access the enrolled courses?</span><span class="qubely-accordion-icon fa fa-plus"></span></span></div><div class="qubely-accordion-body"><div itemprop="text"><!-- wp:paragraph -->
                    <p>Once you're enrolled, you can start learning at any time. If you need to take a short break, you can come back and resume learning from where left. But you have to earn your certificate within 180 days.</p>
                    <!-- /wp:paragraph -->

                    <!-- wp:paragraph -->
                    <p>Please visit our learner’s Manual for more information like how to create an account, how to enroll in a course, and more. <a href="https://drive.google.com/file/d/1wirRc7r9NkLmWnduL9WvHKIL1qhoh6km/preview" target="_blank" rel="noreferrer noopener">Click to view</a></p>
                    <!-- /wp:paragraph --></div></div></div></div>
    <!-- /wp:qubely/accordion-item -->

    <!-- wp:qubely/accordion-item {"uniqueId":"1a60df","itemNumber":5,"heading":"What happens if I don't complete an IOU course?","panelColor":"var(\u002d\u002dqubely-color-3)","panelBg":{"openColor":1,"type":"color","color":"rgba(254,241,243,0.75)","gradient":{"color1":"#EEEEEE","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"panelBgActive":{"openColor":1,"type":"color","color":"#fc8ba1","gradient":{"color1":"#2476CA","color2":"#1A5FA4","direction":0,"start":0,"stop":100,"type":"linear"}},"typography":{"openTypography":false},"panelBorderRadius":{"radiusType":"global","global":{"md":"3"},"unit":"px","openBorderRadius":1},"bodyBg":{"openColor":1,"type":"color","color":"rgba(239,239,239,0.18)","gradient":{"color1":"#f2f2f2","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"borderRadius":{"radiusType":"global","global":{"md":""},"unit":"px","openBorderRadius":1},"spacing":{"md":"25","unit":"px"}} -->
    <div class="wp-block-qubely-accordion-item qubely-block-1a60df"><div class="qubely-accordion-item qubely-type-fill false"><div class="qubely-accordion-panel qubely-icon-position-right"><span class="qubely-accordion-panel-handler" role="button"><span class="qubely-accordion-panel-handler-label">What happens if I don't complete an IOU course?</span><span class="qubely-accordion-icon fa fa-plus"></span></span></div><div class="qubely-accordion-body"><div itemprop="text"><!-- wp:paragraph -->
                    <p>If you do not complete your course and earn a certificate within 180 days, your registration will expire and you will need to pay to re-enroll fee for paid courses.</p>
                    <!-- /wp:paragraph --></div></div></div></div>
    <!-- /wp:qubely/accordion-item -->

    <!-- wp:qubely/accordion-item {"uniqueId":"ea45cb","itemNumber":4,"heading":"How can I pay for a course?","panelColor":"var(\u002d\u002dqubely-color-3)","panelBg":{"openColor":1,"type":"color","color":"rgba(254,241,243,0.75)","gradient":{"color1":"#EEEEEE","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"panelBgActive":{"openColor":1,"type":"color","color":"#fc8ba1","gradient":{"color1":"#2476CA","color2":"#1A5FA4","direction":0,"start":0,"stop":100,"type":"linear"}},"typography":{"openTypography":false},"panelBorderRadius":{"radiusType":"global","global":{"md":"3"},"unit":"px","openBorderRadius":1},"bodyBg":{"openColor":1,"type":"color","color":"rgba(239,239,239,0.18)","gradient":{"color1":"#f2f2f2","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"borderRadius":{"radiusType":"global","global":{"md":""},"unit":"px","openBorderRadius":1},"spacing":{"md":"25","unit":"px"}} -->
    <div class="wp-block-qubely-accordion-item qubely-block-ea45cb"><div class="qubely-accordion-item qubely-type-fill false"><div class="qubely-accordion-panel qubely-icon-position-right"><span class="qubely-accordion-panel-handler" role="button"><span class="qubely-accordion-panel-handler-label">How can I pay for a course?</span><span class="qubely-accordion-icon fa fa-plus"></span></span></div><div class="qubely-accordion-body"><div itemprop="text"><!-- wp:paragraph -->
                    <p>Currently, IOU supports the Paypal gateway. So now the only way to make the payment via PayPal.</p>
                    <!-- /wp:paragraph --></div></div></div></div>
    <!-- /wp:qubely/accordion-item -->

    <!-- wp:qubely/accordion-item {"uniqueId":"605312","itemNumber":5,"heading":"What happens if I fail course completion exam?","panelColor":"var(\u002d\u002dqubely-color-3)","panelBg":{"openColor":1,"type":"color","color":"rgba(254,241,243,0.75)","gradient":{"color1":"#EEEEEE","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"panelBgActive":{"openColor":1,"type":"color","color":"#fc8ba1","gradient":{"color1":"#2476CA","color2":"#1A5FA4","direction":0,"start":0,"stop":100,"type":"linear"}},"typography":{"openTypography":false},"panelBorderRadius":{"radiusType":"global","global":{"md":"3"},"unit":"px","openBorderRadius":1},"bodyBg":{"openColor":1,"type":"color","color":"rgba(239,239,239,0.18)","gradient":{"color1":"#f2f2f2","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"borderRadius":{"radiusType":"global","global":{"md":""},"unit":"px","openBorderRadius":1},"spacing":{"md":"25","unit":"px"}} -->
    <div class="wp-block-qubely-accordion-item qubely-block-605312"><div class="qubely-accordion-item qubely-type-fill false"><div class="qubely-accordion-panel qubely-icon-position-right"><span class="qubely-accordion-panel-handler" role="button"><span class="qubely-accordion-panel-handler-label">What happens if I fail course completion exam?</span><span class="qubely-accordion-icon fa fa-plus"></span></span></div><div class="qubely-accordion-body"><div itemprop="text"><!-- wp:paragraph -->
                    <p>Most IOU courses have personalized schedules that begin when you enroll in a course. You have to accomplish a minimum of 80% marks on the course completion exam/quizzes to avail your certificate. In case you fail at the first attempt, you can retake the exam total 5 times.</p>
                    <!-- /wp:paragraph --></div></div></div></div>
    <!-- /wp:qubely/accordion-item -->

    <!-- wp:qubely/accordion-item {"uniqueId":"173b6f","itemNumber":6,"heading":"Does the IOU certificate have any value?","panelColor":"var(\u002d\u002dqubely-color-3)","panelBg":{"openColor":1,"type":"color","color":"rgba(254,241,243,0.75)","gradient":{"color1":"#EEEEEE","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"panelBgActive":{"openColor":1,"type":"color","color":"#fc8ba1","gradient":{"color1":"#2476CA","color2":"#1A5FA4","direction":0,"start":0,"stop":100,"type":"linear"}},"typography":{"openTypography":false},"panelBorderRadius":{"radiusType":"global","global":{"md":"3"},"unit":"px","openBorderRadius":1},"bodyBg":{"openColor":1,"type":"color","color":"rgba(239,239,239,0.18)","gradient":{"color1":"#f2f2f2","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"borderRadius":{"radiusType":"global","global":{"md":""},"unit":"px","openBorderRadius":1},"spacing":{"md":"25","unit":"px"}} -->
    <div class="wp-block-qubely-accordion-item qubely-block-173b6f"><div class="qubely-accordion-item qubely-type-fill false"><div class="qubely-accordion-panel qubely-icon-position-right"><span class="qubely-accordion-panel-handler" role="button"><span class="qubely-accordion-panel-handler-label">Does the IOU certificate have any value?</span><span class="qubely-accordion-icon fa fa-plus"></span></span></div><div class="qubely-accordion-body"><div itemprop="text"><!-- wp:paragraph -->
                    <p>According to IOU, “Verified Certificates ensure academic integrity" and definitly add values to your portfolio &amp; resume. To improve your skills &amp; learn from an online course, you have take responsibilities in your own hands to complete the course &amp; learn form it.</p>
                    <!-- /wp:paragraph --></div></div></div></div>
    <!-- /wp:qubely/accordion-item -->

    <!-- wp:qubely/accordion-item {"uniqueId":"2019fb","itemNumber":7,"heading":"Do IOU certificates expire?","panelColor":"var(\u002d\u002dqubely-color-3)","panelBg":{"openColor":1,"type":"color","color":"rgba(254,241,243,0.75)","gradient":{"color1":"#EEEEEE","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"panelBgActive":{"openColor":1,"type":"color","color":"#fc8ba1","gradient":{"color1":"#2476CA","color2":"#1A5FA4","direction":0,"start":0,"stop":100,"type":"linear"}},"typography":{"openTypography":false},"panelBorderRadius":{"radiusType":"global","global":{"md":"3"},"unit":"px","openBorderRadius":1},"bodyBg":{"openColor":1,"type":"color","color":"rgba(239,239,239,0.18)","gradient":{"color1":"#f2f2f2","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"borderRadius":{"radiusType":"global","global":{"md":""},"unit":"px","openBorderRadius":1},"spacing":{"md":"25","unit":"px"}} -->
    <div class="wp-block-qubely-accordion-item qubely-block-2019fb"><div class="qubely-accordion-item qubely-type-fill false"><div class="qubely-accordion-panel qubely-icon-position-right"><span class="qubely-accordion-panel-handler" role="button"><span class="qubely-accordion-panel-handler-label">Do IOU certificates expire?</span><span class="qubely-accordion-icon fa fa-plus"></span></span></div><div class="qubely-accordion-body"><div itemprop="text"><!-- wp:paragraph -->
                    <p>No, they don't expire and you can put them in your CV/resume.</p>
                    <!-- /wp:paragraph --></div></div></div></div>
    <!-- /wp:qubely/accordion-item -->

    <!-- wp:qubely/accordion-item {"uniqueId":"8588c8","itemNumber":8,"heading":"Can I retake a course complition exam/quiz?","panelColor":"var(\u002d\u002dqubely-color-3)","panelBg":{"openColor":1,"type":"color","color":"rgba(254,241,243,0.75)","gradient":{"color1":"#EEEEEE","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"panelBgActive":{"openColor":1,"type":"color","color":"#fc8ba1","gradient":{"color1":"#2476CA","color2":"#1A5FA4","direction":0,"start":0,"stop":100,"type":"linear"}},"typography":{"openTypography":false},"panelBorderRadius":{"radiusType":"global","global":{"md":"3"},"unit":"px","openBorderRadius":1},"bodyBg":{"openColor":1,"type":"color","color":"rgba(239,239,239,0.18)","gradient":{"color1":"#f2f2f2","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"borderRadius":{"radiusType":"global","global":{"md":""},"unit":"px","openBorderRadius":1},"spacing":{"md":"25","unit":"px"}} -->
    <div class="wp-block-qubely-accordion-item qubely-block-8588c8"><div class="qubely-accordion-item qubely-type-fill false"><div class="qubely-accordion-panel qubely-icon-position-right"><span class="qubely-accordion-panel-handler" role="button"><span class="qubely-accordion-panel-handler-label">Can I retake a course complition exam/quiz?</span><span class="qubely-accordion-icon fa fa-plus"></span></span></div><div class="qubely-accordion-body"><div itemprop="text"><!-- wp:paragraph -->
                    <p>Usually you can retake course completion exam/quiz upto 5 times incase you fail. </p>
                    <!-- /wp:paragraph --></div></div></div></div>
    <!-- /wp:qubely/accordion-item -->

    <!-- wp:qubely/accordion-item {"uniqueId":"b287a7","itemNumber":9,"heading":"Who should I contact for support?","panelColor":"var(\u002d\u002dqubely-color-3)","panelBg":{"openColor":1,"type":"color","color":"rgba(254,241,243,0.75)","gradient":{"color1":"#EEEEEE","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"panelBgActive":{"openColor":1,"type":"color","color":"#fc8ba1","gradient":{"color1":"#2476CA","color2":"#1A5FA4","direction":0,"start":0,"stop":100,"type":"linear"}},"typography":{"openTypography":false},"panelBorderRadius":{"radiusType":"global","global":{"md":"3"},"unit":"px","openBorderRadius":1},"bodyBg":{"openColor":1,"type":"color","color":"rgba(239,239,239,0.18)","gradient":{"color1":"#f2f2f2","color2":"#e5e5e5","direction":0,"start":0,"stop":100,"type":"linear"}},"borderRadius":{"radiusType":"global","global":{"md":""},"unit":"px","openBorderRadius":1},"spacing":{"md":"25","unit":"px"}} -->
    <div class="wp-block-qubely-accordion-item qubely-block-b287a7"><div class="qubely-accordion-item qubely-type-fill false"><div class="qubely-accordion-panel qubely-icon-position-right"><span class="qubely-accordion-panel-handler" role="button"><span class="qubely-accordion-panel-handler-label">Who should I contact for support?</span><span class="qubely-accordion-icon fa fa-plus"></span></span></div><div class="qubely-accordion-body"><div itemprop="text"><!-- wp:paragraph -->
                    <p>If you have any quires or need any help for IOU team, feel free to email at <span class="has-inline-color has-pale-pink-color">info@iou.ac</span></p>
                    <!-- /wp:paragraph --></div></div></div></div>
    <!-- /wp:qubely/accordion-item --></div>
